# Generated by Django 5.2.16 on 2026-08-11 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('origin_city', models.CharField(max_length=100)),
                ('origin_lat', models.FloatField(default=0.0)),
                ('origin_lng', models.FloatField(default=0.0)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_lat', models.FloatField(default=0.0)),
                ('destination_lng', models.FloatField(default=0.0)),
                ('equipment_type', models.CharField(choices=[('Dry Van', 'Dry Van'), ('Reefer', 'Reefer'), ('Flatbed', 'Flatbed'), ('Stepdeck', 'Stepdeck'), ('Box Truck', 'Box Truck')], default='Dry Van', max_length=50)),
                ('weight_lbs', models.IntegerField(help_text='Weight in LBS')),
                ('max_budget', models.DecimalField(decimal_places=2, help_text='Total budget USD', max_digits=10)),
                ('pickup_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MATCHED', 'Matched'), ('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('document_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('truck_number', models.CharField(max_length=50)),
                ('equipment_type', models.CharField(choices=[('Dry Van', 'Dry Van'), ('Reefer', 'Reefer'), ('Flatbed', 'Flatbed'), ('Stepdeck', 'Stepdeck'), ('Box Truck', 'Box Truck')], default='Dry Van', max_length=50)),
                ('max_capacity_lbs', models.IntegerField(help_text='Max payload capacity in LBS')),
                ('current_city', models.CharField(max_length=100)),
                ('current_lat', models.FloatField(default=0.0)),
                ('current_lng', models.FloatField(default=0.0)),
                ('target_city', models.CharField(blank=True, max_length=100, null=True)),
                ('target_lat', models.FloatField(default=0.0)),
                ('target_lng', models.FloatField(default=0.0)),
                ('min_rate_per_mile', models.DecimalField(decimal_places=2, default=2.5, max_digits=8)),
                ('available_date', models.DateField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20)),
                ('truck_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('license_doc_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='Match score percentage (0-100)')),
                ('breakdown', models.JSONField(default=dict, help_text='Detailed score metrics')),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PROPOSED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='trucklink_api.load')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='trucklink_api.truck')),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
            },
        ),
    ]
