import React,{useEffect,useState} from "react";
import { AlertCircle, Edit, RefreshCw } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { driverApi } from "../../api/drivers";
import { getApiErrorMessage } from "../../api/client";
import AppHeader from "../layout/AppHeader";
import StatusBadge from "../ui/StatusBadge";
import LoadingState from "../ui/LoadingState";

const DriverStatusTracking=()=>{const nav=useNavigate();const [profile,setProfile]=useState(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const load=async()=>{setLoading(true);setError("");try{const{data}=await driverApi.getMyProfile();setProfile(data);}catch(e){const s=e.response?.status;if(s===404||s===500){setError("No driver profile could be loaded. If this is a new account, create your profile first.");}else setError(getApiErrorMessage(e,"Unable to load profile."));}finally{setLoading(false);}};useEffect(()=>{load();},[]);return <div className="min-h-screen bg-[#f7f4ea]"><AppHeader title="TruckLink Driver" subtitle="Profile status" actions={<button onClick={load} className="rounded-xl bg-[#2d6a4f] p-2.5 text-white"><RefreshCw className="h-4 w-4"/></button>}/><main className="mx-auto max-w-5xl p-4 py-8 sm:px-6">{loading?<LoadingState label="Loading your profile..."/>:error?<div className="rounded-3xl border border-amber-200 bg-[#fff8e8] p-6"><div className="flex gap-3"><AlertCircle className="h-5 w-5 text-amber-700"/><div><h2 className="font-bold text-[#604d25]">Profile unavailable</h2><p className="mt-1 text-sm text-[#76643f]">{error}</p><button onClick={()=>nav("/driver/profile")} className="mt-4 rounded-xl bg-[#2d6a4f] px-4 py-2.5 text-sm font-bold text-white">Create profile</button></div></div></div>:<div className="space-y-5"><section className="rounded-3xl border border-[#e7dfca] bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-widest text-[#2d6a4f]">Moderation status</p><h1 className="mt-1 text-3xl font-black text-[#203d31]">{profile.full_name}</h1><div className="mt-3"><StatusBadge status={profile.status}/></div></div><button onClick={()=>nav("/driver/profile")} className="inline-flex items-center gap-2 rounded-xl border border-[#d9e4dd] px-4 py-2.5 text-sm font-semibold text-[#446557]"><Edit className="h-4 w-4"/>Profile form</button></div>{profile.status_reason&&<div className="mt-5 rounded-2xl bg-[#fff8e8] p-4"><p className="text-xs font-bold uppercase text-[#8b7135]">Admin feedback</p><p className="mt-1 text-sm text-[#66552f]">{profile.status_reason}</p></div>}</section><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[["Phone",profile.phone],["CDL class",profile.cdl_class],["Experience",`${profile.years_experience} years`],["Availability",profile.availability],["Preferred region ID",profile.preferred_region??"—"],["Updated",profile.updated_at?new Date(profile.updated_at).toLocaleString():"—"]].map(([l,v])=><div key={l} className="rounded-2xl border border-[#e7dfca] bg-[#fffdf8] p-5"><p className="text-xs font-bold uppercase tracking-wide text-[#849087]">{l}</p><p className="mt-2 font-semibold text-[#29483a]">{v||"—"}</p></div>)}</section></div>}</main></div>};
export default DriverStatusTracking;
