# Generated by Django 6.1 on 2026-08-10 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('shortlisted', 'Shortlisted'), ('contacted', 'Contacted')], default='shortlisted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='drivers.driverprofile')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='recruiters.jobposting')),
            ],
            options={
                'unique_together': {('job_posting', 'driver_profile')},
            },
        ),
    ]
