# Generated by Django 6.1 on 2026-08-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='initiated_by',
            field=models.CharField(choices=[('driver', 'Driver'), ('recruiter', 'Recruiter')], default='driver', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('contacted', 'Contacted')], default='applied', max_length=20),
        ),
    ]
